FROM mwader/static-ffmpeg:latest AS ffmpeg-binaries
FROM debian:trixie-slim

ARG VERSION
ARG BUILD_DATE

LABEL version="${VERSION}"
LABEL build_date="${BUILD_DATE}"
LABEL maintainer="Chaos7x"
LABEL purpose="YouTube upload automation with ffmpeg + mc + inotify"

# ==========================================
# STUFE 1: Statische Binaries kopieren (Dauert 0 Sekunden)
# ==========================================
COPY --from=ffmpeg-binaries /ffmpeg /usr/local/bin/ffmpeg
COPY --from=ffmpeg-binaries /ffprobe /usr/local/bin/ffprobe

# ==========================================
# STUFE 2: Noch mc und inotify über apt holen, sowie python Abhängigkeiten 
# ==========================================
RUN apt-get update && apt-get install -y  --no-install-recommends \
    mc \
    inotify-tools \
    jq \
    libimage-exiftool-perl \
    python3-requests \
    python3-inotify \
    && rm -rf /var/lib/apt/lists/*

# ==========================================
# STUFE 4: Arbeitsverzeichnis & Rechte
# ==========================================
WORKDIR /app
# RUN chmod 777 /app
# RUN mkdir .cache .config .local && chmod 777 .cache .config .local

# Neues, separates Datenverzeichnis für deine Videos erstellen und freigeben
RUN mkdir /videos && chmod 777 /videos

# Log Verzeichnis erstellen und freigeben
RUN mkdir /log && chmod 777 /log

# ==========================================
# STUFE 5: Deine lokalen Skripte & Configs
# ==========================================
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY yt-upload_pyav.py /usr/local/bin/yt-upload
COPY get_token.py /usr/local/bin/get_token
RUN chmod +x /usr/local/bin/yt-upload /usr/local/bin/entrypoint.sh /usr/local/bin/get_token

# .bashrc kopieren und Symlink nach /tmp legen
COPY bashrc /etc/global.bashrc
RUN ln -s /etc/global.bashrc /tmp/.bashrc
RUN ln -s /etc/global.bashrc /app/.bashrc

ENV HOME=/app

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
