#!/bin/sh
### BEGIN INIT INFO
# Provides:          yt-upload
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Automatisierter YouTube Upload Workflow
# Description:       Startet yt-upload im Daemon-Modus (-D). Nur fuer
#                     Systeme ohne systemd (z.B. Devuan, Debian mit
#                     sysvinit-core) - auf einem systemd-Host wird stattdessen
#                     yt-upload.service verwendet, dieses Skript wird dort
#                     gar nicht erst registriert (siehe daemon-postinst.sh).
#                     Fuer den optionalen periodischen Retry-Requeue (SysV-
#                     Pendant zu yt-upload-retry.timer) siehe
#                     yt-upload-retry.cron.example.
### END INIT INFO

set -e

NAME=yt-upload
DAEMON=/usr/bin/yt-upload
DAEMON_ARGS="-D"
PIDFILE=/run/$NAME.pid
RUN_AS=yt-upload

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

do_start() {
    # --background: yt-upload daemonisiert sich nicht selbst (laeuft im
    # Vordergrund, wie unter systemd Type=simple) - start-stop-daemon
    # uebernimmt das Forken. --chuid ruft initgroups() fuer RUN_AS auf,
    # wodurch auch die media-pipeline-Zusatzgruppe (siehe daemon-postinst.sh)
    # greift, genau wie SupplementaryGroups= in yt-upload.service.
    start-stop-daemon --start --quiet --background --make-pidfile \
        --pidfile "$PIDFILE" --chuid "$RUN_AS:$RUN_AS" \
        --exec "$DAEMON" --test > /dev/null \
        || return 1
    start-stop-daemon --start --quiet --background --make-pidfile \
        --pidfile "$PIDFILE" --chuid "$RUN_AS:$RUN_AS" \
        --exec "$DAEMON" -- $DAEMON_ARGS \
        || return 2
}

do_stop() {
    # --retry=TERM/10/KILL/5: erst SIGTERM (der Daemon nimmt danach keine
    # neue Datei mehr an, laesst eine laufende Chunk-Upload-Runde aber
    # fertig werden, siehe daemon.py), erst nach 10s Wartezeit ohne Erfolg
    # SIGKILL als letzter Ausweg - ein Kill mitten im Chunk ist dank des
    # Resumable-Upload-Protokolls ohnehin unkritisch.
    start-stop-daemon --stop --quiet --retry=TERM/10/KILL/5 --pidfile "$PIDFILE"
    RETVAL="$?"
    rm -f "$PIDFILE"
    return "$RETVAL"
}

case "$1" in
  start)
    log_daemon_msg "Starting $NAME" "$NAME"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $NAME" "$NAME"
    do_stop
    log_end_msg $?
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting $NAME" "$NAME"
    do_stop
    do_start
    log_end_msg $?
    ;;
  status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 3
    ;;
esac

exit 0
